ci:
  # https://github.com/pre-commit-ci/issues/issues/83
  autoupdate_schedule: quarterly
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext", "md"]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.0.3"
    hooks:
      - id: editorconfig-checker
        alias: ec
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.3
    hooks:
      - id: check-renovate
        additional_dependencies: ["pyjson5"]
